version: "3.7"

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    restart: "no"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=persons
      - MYSQL_USER=theuser
      - MYSQL_PASSWORD=thepassword
    command: --max_connections=250
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=toor --execute 'select count(*) from persons.person;' || exit 1"]
      interval: 15s
      timeout: 2s
      retries: 5
      start_period: 15s

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"
