server:
  shutdown: graceful

spring:
  application:
    name: spring-kafka-21-simple

  kafka:
    consumer:
      group-id: default-spring-consumer3
      auto-offset-reset: earliest

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,applicationShutdown