
package com.app.ch09.xml.myws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyCalculator", targetNamespace = "http://myws.xml.ch09.app.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyCalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://myws.xml.ch09.app.com/", className = "com.app.ch09.xml.myws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://myws.xml.ch09.app.com/", className = "com.app.ch09.xml.myws.AddResponse")
    @Action(input = "http://myws.xml.ch09.app.com/MyCalculator/addRequest", output = "http://myws.xml.ch09.app.com/MyCalculator/addResponse")
    public int add(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

}
