version: "3.7"

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3307:3306"
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=persons
      - MYSQL_USER=theuser
      - MYSQL_PASSWORD=thepassword
    command: --max_connections=250
