version: "3.7"

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    restart: "no"
    volumes:
      - "./mysql-init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=H5GGame
      - MYSQL_USER=electrosvc
      - MYSQL_PASSWORD=electrosvc
    command: --max_connections=250
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=toor --execute 'select count(1) from H5GGame.GameData;' || exit 1"]
      interval: 15s
      timeout: 2s
      retries: 5
      start_period: 15s

  hazelcast-man-center:
    image: hazelcast/management-center:3.12.6
    container_name: hazelcast-man-center
    restart: "no"
    ports:
      - "8080:8080"
    volumes:
      - "./tmp/hazelcast-man-center:/data"
    environment:
      - MAX_HEAP_SIZE=512m

  hazelcast1:
    image: hazelcast/hazelcast:3.12.6
    container_name: hazelcast1
    depends_on:
      - hazelcast-man-center
    restart: "no"
    ports:
      - "5701:5701"
    volumes:
      - "./hazelcast:/opt/hazelcast/config_ext"
    environment:
      - JAVA_OPTS="-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml"
      - MAX_HEAP_SIZE=512m

  relax-malta-1:
    build: ./
    container_name: relax-malta-1
    image: relax-malta
    depends_on:
      - hazelcast1
      #      - hazelcast2
      - mysql
    restart: "no"
    volumes:
      - "./tmp/electro1/log:/var/log/electro"
      - "./config:/opt/electro/config/"
      - "./lib:/opt/electro/lib/"
      - "./slots:/opt/electro/slots/"
    ports:
      - "8449:8449"
      - "7203:7203"
      - "7204:7204"
      - "8081:8080"
      - "5006:5005"
    environment:
      - UGP_ENVIRONMENT=DOCKER-COMPOSE
      - HOST_IP=localhost
      - MIN_MEMORY=512m
      - MAX_MEMORY=1g

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"

