version: "3.7"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-secrets
    ports:
      - "3306:3306"
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD_FILE='/run/secrets/mysql.txt'
      - MYSQL_DATABASE=persons
      - MYSQL_USER=theuser
      - MYSQL_PASSWORD=thepassword
    command: --max_connections=250

secrets:
  mysql.txt:
    external:true
